version = 0.1

[default.global.parameters]
region = "ap-southeast-1"

[staging.global.parameters]
stack_name = "kamelott-staging"
region = "ap-southeast-1"

[staging.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
force_upload = true

[prod.global.parameters]
stack_name = "kamelott-prod"
region = "ap-southeast-1"

[prod.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
force_upload = true
confirm_changeset = true
